# PyTorch Fundamentals (Chapter 12)

---

This notebook covers the **fundamental operations and structures in PyTorch** as introduced in the initial sections of Chapter 12 of the Raschka book ("Python Machine Learning").

### Core Concepts Demonstrated:

* **Tensor Creation & Conversion:** Demonstrations of creating tensors from Python lists and NumPy arrays (`torch.tensor()`, `torch.from_numpy()`), and creating specialized tensors like those filled with ones (`torch.ones()`) or random integers (`torch.randint()`).
* **Attributes & Casting:** Checking the shape (`.shape`) and data type (`.dtype`) of tensors, and changing the data type (`.to(torch.float32)`).
* **Tensor Manipulation (Reshaping):**
    * **Transposition:** Using `.transpose(0, 1)` to swap dimensions.
    * **Reshaping:** Changing the tensor view with `torch.reshape()`.
    * **Squeezing:** Removing a singleton dimension with `torch.squeeze()`.
* **Mathematical Operations:**
    * **Element-wise:** Multiplication (`torch.multiply()`).
    * **Reduction:** Calculating statistics across dimensions (mean, sum, standard deviation: `torch.mean()`, `torch.sum()`, `.std()`).
    * **Matrix Multiplication:** `torch.matmul()`.
    * **Norm:** Calculating the $L_2$ norm (`torch.linalg.norm()`).
* **Splitting and Joining:**
    * **Splitting:** Dividing a tensor into chunks (`t.chunk()`, `torch.split()`).
    * **Joining:** Concatenating (`torch.cat()`) and stacking (`torch.stack()`) tensors along a specified axis.
* **Data Handling:** Introduction to the `DataLoader` class for iterating over tensor data, including using `batch_size`.

In [2]:
import torch
import numpy as np

In [5]:
np.set_printoptions(precision= 3)
a = [1, 2, 3]
b = np.array([4, 5, 6], dtype= np.int32)
t_a = torch.tensor(a)
t_b = torch.from_numpy(b)
print(t_a)
print(t_b)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [8]:
ones = torch.ones(2, 3)
print(ones.shape)
print(ones)

torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [32]:
rand_tensor = torch.randint(2, (3,10))
print(rand_tensor)

tensor([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 1, 0, 1, 1, 0, 0, 0, 1, 0]])


In [30]:
rand_float = rand_tensor.to(torch.float32)
print(rand_float.dtype)

torch.float32


In [46]:
t = torch.rand(4, 5)
t_tr = t.transpose(0, 1)
print(f'{t.shape} ---> {t_tr.shape}')

torch.Size([4, 5]) ---> torch.Size([5, 4])


In [52]:
t = torch.zeros(30)
t_r = torch.reshape(t, [5, 6])
print(f'{t}\n{t_r}')

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.])
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


In [66]:
t = torch.zeros(1, 2, 1, 4, 2)
t_sq = torch.squeeze(t, 2)
print(f'{t_sq}\n{t_sq.shape}')

tensor([[[[0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.]]]])
torch.Size([1, 2, 4, 2])


In [70]:
torch.manual_seed(1)
t1 = 2 * torch.rand(5, 2) - 1
t2 = torch.normal(mean= 0, std= 1, size= (5, 2))
print(t1, t2)

tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]]) tensor([[ 0.8590,  0.7056],
        [-0.3406, -1.2720],
        [-1.1948,  0.0250],
        [-0.7627,  1.3969],
        [-0.3245,  0.2879]])


In [72]:
t3 = torch.multiply(t1, t2)
print(t3)

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])


In [76]:
mean = torch.mean(t3, axis= 0)
sum_t = torch.sum(t3, axis= 1)
std = t3.std(axis= 0)
print(mean, sum_t, std)

tensor([ 0.3491, -0.0436]) tensor([ 0.1312, -0.5310,  1.1399,  0.8676, -0.0804]) tensor([0.4698, 0.4875])


In [77]:
t4 = torch.matmul(t3, t1.transpose(0, 1))
print(t4)

tensor([[ 0.3655, -0.2320, -0.6035, -0.2495,  0.0997],
        [ 0.2975, -0.2930, -0.4202, -0.3173,  0.0823],
        [ 0.5730, -0.2110, -1.0500, -0.2238,  0.1545],
        [-0.2328,  0.3032,  0.2785,  0.3293, -0.0652],
        [-0.0077, -0.0078,  0.0213, -0.0087, -0.0020]])


In [78]:
t5 = torch.matmul(torch.transpose(t3, 0, 1), t2)
print(t5)

tensor([[-1.0913,  0.4627],
        [-0.6127,  1.5227]])


In [79]:
norm_t = torch.linalg.norm(t1, ord= 2, dim= 1)
norm_t

tensor([0.6785, 0.5078, 1.1162, 0.5488, 0.1853])

In [91]:
t = torch.rand(8)
t_chunk = t.chunk(5)
t_chunk

(tensor([0.3486, 0.9579]),
 tensor([0.4075, 0.7819]),
 tensor([0.7165, 0.1768]),
 tensor([0.0748, 0.9799]))

In [92]:
t = torch.rand(7)
t_split = torch.split(t, split_size_or_sections=[2, 3, 2])
t_split

(tensor([0.5261, 0.8427]),
 tensor([0.6036, 0.6608, 0.8735]),
 tensor([0.9741, 0.1682]))

In [102]:
t1 = torch.zeros(3, 2)
t2 = torch.ones(3, 2)
t_c = torch.cat([t1, t2], axis= -1)
t_c

tensor([[0., 0., 1., 1.],
        [0., 0., 1., 1.],
        [0., 0., 1., 1.]])

In [105]:
t_s = torch.stack([t1, t2], axis= 0)
t_s

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [118]:
from torch.utils.data import DataLoader   
t = torch.arange(7, dtype= torch.float32)
dataloader = DataLoader(t)

In [111]:
for i in dataloader:
    print (i)

tensor([0.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([4.])
tensor([5.])


In [125]:
dataloader = DataLoader(t, batch_size= 2, drop_last= False)
for item in dataloader:
    print(item)

tensor([0., 1.])
tensor([2., 3.])
tensor([4., 5.])
tensor([6.])
